### ISSUE TITLE
Should.Throw and dynamic

### ISSUE THREAD

**Issue by asgerhallas** [shouldly/shouldly#133]
I have troubles with dynamic in some shouldly tests. If I do this:

```
    protected override void ShouldPass()
    {
        Should.Throw<NotImplementedException>(() => ((dynamic)this).Thrower());
    }

    public void Thrower()
    {
        throw new NotImplementedException();
    }
```

it fails. I can look into it, if you want me to :)

**Comment by caioproiete** [comment]
Hi,

Had a quick look at this issue, and a `RuntimeBinderException` is being thrown because the C# compiler is choosing to call the overload that receives a `Func<Task>` instead of the overload that receives an `Action` which was intended one.

So a workaround is to cast the lambda expression to `Action`, and it all works as expected:
```
protected override void ShouldPass()
{
    Should.Throw<NotImplementedException>((Action)(() => ((dynamic)this).Thrower()));
}
```

Not sure what the best fix would be (if any). We could try to implement a dynamic version of the `Throw<T>` method in the `DynamicShould`, or maybe inspect if the actual is dynamic when the `Func<T>` is called, and try to handle accordingly (before the binding happens).

Thoughts?

**Comment by JoeMighty** [comment]
Thanks for looking into this one @caioproiete!

I think the first suggestion (implement a dynamic version of the Throw<T> method in the DynamicShould) sounds like the cleanest approach personally, though I'd be interested in hearing others' thoughts? @JakeGinnivan ?

**Comment by nasirodin** [comment]
Hey I am a first-timer looking for tasks to do . Could I jump in and help with this issue?

**Comment by JosephWoodward** [comment]
Hi @nasirodin, please by all means feel free to take a stab at this issue :)

**Comment by nasirodin** [comment]
@JosephWoodward  thank you :)

**Comment by KonH** [comment]
@JosephWoodward Hello! I made PR which covers that case, please review it. Any feedback will be appreciated!
