### ISSUE TITLE
Allow custom/additional message to ShouldlyMessage

### ISSUE THREAD

**Issue by aaronpowell** [shouldly/shouldly#190]
I think this is related to #52 but figured I'd like to add it anyway.

I'd **really** like a way to provide a custom message to the 'assert' that is executed.

Scenario:

> I am doing a HTTP Request, I expect an `OK` response, I get `Internal Server Error`. I'd like to add to the message the server response.

Here's a sample of how I'd see the API working:

    [Fact]
    public async Task Should_return_OK() {
        var response = await GetAsync("/api/something");
        
        response.StatusCode.ShouldBe(HttpStatusCode.OK, () => response.Content.ReadAsStringAsync().Result);
    }

Notice the use of the lambda for the additional message, this prevents the code from being executed unless the Should fails, so if you're doing something complex or that has side effects (ie - reading the a HTTP response) it will only be done if needed.

The invocation of the lambda should be in a `try/catch` itself and if it throws just do a `Debug.WriteLine` with the exception (or something similar) and add something to the output message that the additional message failed.

**Comment by fekberg** [comment]
I like the idea of having extra information in the ShouldlyMessage, just a small note on the asynchronous part where you are forcing a block. That code might deadlock, which isn't ideal. It's generally bad practice to force a wait/blocking.

You could change it in two ways.

**Async all the way**
`response.StatusCode.ShouldBe(HttpStatusCode.OK, async () => await response.Content.ReadAsStringAsync());`

**Force block and avoid deadlock**
This is a bit of a "hack" but will result in the wanted behaviour of blocking code. The reason you wrap it in a new Task is so that you are not locking the Task/Thread where the signal of the async completion will be notified to. In ASP.NET this also avoids capturing the `SynchronizationContext`.

`response.StatusCode.ShouldBe(HttpStatusCode.OK, () => Task.Run(() => response.Content.ReadAsStringAsync()).Result);`

**Comment by robdmoore** [comment]
+1 I've wanted custom messages a couple of times. This example being one of them actually!

I'd want a string overload as well as the lambda though.

**Comment by PureKrome** [comment]
Blammo! same here @aaronpowell and @robdmoore

**Comment by pawelpabich** [comment]
+1 one for simple string overload

**Comment by aaronpowell** [comment]
@fekberg just having a quick dig into the code, it supports .NET 3.5, would that have any problem with the async/await stuff?

**Comment by fekberg** [comment]
@aaronpowell TPL was introduced in .NET 4.0 and async/await in .NET 4.5. You won't want to make Shouldly know about TPL/async&await just think about it when you consume it from an application that uses async & await.

**Comment by JakeGinnivan** [comment]
@fekberg we have `#IF NET40` to turn on the task support in the .net 40 builds.

What I am hearing is the following overloads

``` csharp
.ShouldBe(this object actual, object expected)
.ShouldBe(this object actual, object expected, string customMessage)
.ShouldBe(this object actual, object expected, Func<string> customMessage)
.ShouldBe(this object actual, object expected, Task<string> customMessage)
```

Also @fekberg we use the `Task.Run(() => ...)` trick in `Should.Throw(Task<T>)` to make sure the lambda is run without a sync context then we block and wait for completion. #172 is tracking adding a `Should.ThrowAsync()` overload which is asynchronous. 

Any volunteers? :P

**Comment by JakeGinnivan** [comment]
#169 is similar to this, except the task/func overloads are not in that one

**Comment by JakeGinnivan** [comment]
@fekberg the ShouldThrow task support code: https://github.com/shouldly/shouldly/blob/master/src/Shouldly/ShouldThrowTaskExtensions.cs

**Comment by aaronpowell** [comment]
@JakeGinnivan looking into the source there's currently 11 `.ShouldBe` methods. To support all 3 _styles_ there will be 33 `.ShouldBe` methods. In fact there's 33 methods in `ShouldBeTestExtensions`, which then becomes 99 methods.

This is why I suggested just the `Func<string>` property, which could be defaulted to `null` (or `() => string.Empty`) which is easy for use with all scenarios from just adding additional test:

    foo.ShouldBe("something", () => "The value of foo wasn't something");

To combining with a task:

    foo.ShouldBe("something", () => Task.Run(() => doAsync()).Result);

**Comment by aaronpowell** [comment]
PR opened with some initial work on this implementation. Since the test project is .NET 4.0 I'm not sure how to do `Task.Run`, @fekberg - any opinions?

**Comment by xerxesb** [comment]
I'm typically pretty quiet now-a-days about the direction of Shouldly, but one thing that bugs me about this thread is that there hasn't been any discussion about the assertion failure message itself.

Shouldly differentiated itself from other assertion frameworks because failure messages were contextual and the actual error was human readable, where other frameworks typically left the developer to mentally parse out the error from the assertion failure message. 

Maybe i'm missing it, and it's already been considered and taken care of (in which case feel free to ignore me), but please keep this at the front of your minds when designing new APIs. The presentation of the assertion failure message is just as important as the API itself.

**Comment by aaronpowell** [comment]
@xerxesb Sure, I get that that's what Shouldly is about, useful messages without you having to write them yourself. The problem that can happen comes back to what you mention, context. Sometimes context requires more information than can be gained from the particular object you're asserting against, as in my original example.

Here's an example from our build server:

    Shouldly.ChuckedAWobbly : 
         var messages = await message.Content.ReadAsAsync<IEnumerable<ApiMessage>>();

                 messages.Count()
             should be
         HttpStatusCode.BadRequest
             but was
         HttpStatusCode.Forbidden

The test body looks like so:

    var message = await PutAsync(Urls.Administration.Alert(Id), new EventAlertDefinitionModel
                {
                    ...
                });
    message.StatusCode.ShouldBe(HttpStatusCode.BadRequest);

    var messages = await message.Content.ReadAsAsync<IEnumerable<ApiMessage>>();

    messages.Count().ShouldBe(1);

There's a bit of context lost here that I'd like to add in the event of failure, what was the response body for example.

Sure I could use some other assert framework but then that means I've got two ways to do asserts which is just a PIA.

I understand and respect the goals of Shouldly, I'm just looking for options on how to make it even better for those edge-cases where context is more uniquely defined.

**Comment by xerxesb** [comment]
> I'm just looking for options on how to make it even better for those edge-cases where context is more uniquely defined.

:+1:

**Comment by pawelpabich** [comment]
This is ugly and I'm not sure whether it is even possible, but it will not require us to create any new overloads. actualValue.WithAdditionalMessage("details").ShouldBe(expectedValue);

**Comment by aaronpowell** [comment]
Shouldly is extension methods on top of `object` so you'd need to introduce a proxy object which might get funky

**Comment by fekberg** [comment]
@aaronpowell in .NET 4.0 you'd do `Task.StartNew`. `Run` was added later, as a short hand for that!

**Comment by JakeGinnivan** [comment]
@xerxesb this is similar to #169 which specifies the messages.

My thoughts were simple add:

```
Additional information:
<my custom message>
```

Under what we have already, this way we still get the full shouldly error but some additional context
