### ISSUE TITLE
Should.CompleteIn() displays Task total completion time

### ISSUE THREAD

**Issue by JulienFiaffe** [shouldly/shouldly#255]
When "playing" with the `Should.CompleteIn()` method I noticed that the error message is something like:

```
Task
    should complete in
00:00:01
    but did not
```

I wonder if it can be helpful to display the total completion time for the Task under test and having the following kind of error message instead:

```
Task
    should complete in
00:00:01
    but completed in
00:00:02
```

This will allow to see if the difference is important or not, to distinguish massive time increase from small ones.

I understand it would require some refactoring to change the inner behavior of the library regarding this topic.
I don't know if working with the `StopWatch` class can have drawbacks for this, especially if the Task under test never ends, so does the test without a timeout.

This is an open question, let me know what you think for this improvement.

**Comment by JoeMighty** [comment]
Sounds like a good idea to me. Interested to hear everyone else's thoughts on this.

**Comment by JakeGinnivan** [comment]
CompleteIn is one of those things which are there for some cases where you are testing code which could timeout. Since adding this I have been reading more about xUnits thoughts around this and why [Timeout] was removed. Timing is something which is not good to test as it is not absolute, different execution times due to many factors could cause false positives.

This is an example of why it could be a good thing to remove in the next major. We use it internally for timing out Tasks because we have made them block.

What are the scenarios you are using this for?

**Comment by JulienFiaffe** [comment]
I do not have any particular scenario for this case at the moment.
I was just wondering if it could be helpful, to detect massive loss of performance on a given method.
But I agree with you regarding the fact that testing execution time can cause false positives.

**Comment by SimonCropp** [comment]
@JulienFiaffe  given you dont have a specific use case for this. perhaps it is best to close it for now, and re-visit if someone can articulate a real use case?

**Comment by JulienFiaffe** [comment]
@SimonCropp given it has been 5 years without any new input, I do not mind closing this issue.
Doing it now, thank you for the reminder.
