### ISSUE TITLE
Impelement ShouldThrowWithInnerException() 

### ISSUE THREAD

**Issue by ceregador** [shouldly/shouldly#277]
_ShouldThrowWithInnerException`<TException, TInnerException>`()_
Asserts that the thrown exception of type TException contains an inner exception of type TInnerException.

_ShouldThrowWithInnerExceptionExactly`<TException, TInnerException>`()_
Asserts that the thrown exception of type TException contains an inner exception of the exact type TInnerException (and not a derived exception type).

**Comment by JakeGinnivan** [comment]
I think these Throw overloads complicate the API and increases the complexity of the error messages. Think about the error message for this, would have to be something like `... should throw TException with an inner exception which derives from TInnerExeption but threw TException with inner exception type of TOtherException` 

Shouldly's API makes an effort not to have multiple possible errors conflated into a single assertion message. The way I would do this is:

``` csharp
var ex = Should.Throw<TException>();
ex.InnerException.ShouldBeOfType<TInnerException>();
```

Feel free to continue the discussion on this issue, but am going to close this one for now.

**Comment by TsengSR** [comment]
@JakeGinnivan: Is there still no alternative to it?

The reason/use case I'd have is, when testing a class which involves throwing in constructor, I usually use AutoMocks for it. The issue here is, that the IoC container in the unit tests may not necessarily be the same as in the main application (i.e.  as far as I know there's no Automock for the default Microsoft.Extensions.DepedencyInjection, so for unit tests I fall back to Autofac.Extra.Moq to instantiate the SUT via dependency injection (all dependencies will be injected as either the registered objects or mocks if there is no registration for it). 

But depending on the IoC used, the exception thrown will be different (i.e. Autofac throws `Autofac.Core.DependencyResolutionException` which is nested and contains another `Autofac.Core.DependencyResolutionException` in it and only then on the 2nd InnerException is the actual exception. 

Now I am actually **not interested** in the wrapped excpetions but only in the concrete Exception (in this case `InvalidOperationException`). Setting up unit tests is somewhat of a pain because of this. 

In that case, this code won't work

```
InvalidOperationException exception = Should.Throw<InvalidOperationException>(() =>
{
    ReferenceResolverProvider resolverProvider = mock.Create<ReferenceResolverProvider>();
});
```
It would be nice if we could have a method that can be used like 

```
InvalidOperationException exception = Should.ThrowsOneOf<InvalidOperationException>(() =>
{
    ReferenceResolverProvider resolverProvider = mock.Create<ReferenceResolverProvider>();
});
```
which will check if the `InvalidOperationException is thrown or is nested somewhere within the inner exceptions.

**Comment by JakeGinnivan** [comment]
Hey, to be honest I haven't worked with shouldly (or .net) for a few years now. I will have to delegate to the newer maintainers
