### ISSUE TITLE
Implemement ShouldBeInOrder(Direction.Ascending|Descending | IComparer) for IEnumerable

### ISSUE THREAD

**Issue by ceregador** [shouldly/shouldly#280]
_ShouldBeInDescendingOrder()_
Expects the current collection to have all elements in descending order. Elements are compared using their IComparable.CompareTo(System.Object) implementation.

_ShouldNotBeDescendingInOrder()_
Asserts the current collection does not have all elements in descending order. Elements are compared using their IComparable.CompareTo(System.Object) implementation.

**Comment by JakeGinnivan** [comment]
Convince me that this is better than `enumerable.OrderBy(_ => _).ShouldBe(enumerable)` or `enumerable.OrderByDescending(_ => _).ShouldBe(enumerable)`. Especially as we need to add overloads to allow to compare using a different key?

**Comment by JakeGinnivan** [comment]
Going to close for the moment. Don't think the work is worth it and nobody has asked for it

**Comment by SurajGupta** [comment]
@JakeGinnivan - diagree with your assessment here.  The LINQ/lambda method is far less readable than ShouldBeInAscendingOrder.  For other bugs like length of string, str.Length.ShouldBe(x) makes sense because its highly readable.  The difference is in the operation.  What you're saying is "when I apply an orderby operation on an enumerable it should be equal to this other enumerable"  versus says "this enumerable should be in ascending order"

**Comment by JakeGinnivan** [comment]
I was on the fence on this one, which is why I asked to be convinced. Fluent assertions has the benefit of a fluent interface which can chain different types of exceptions off extension points so you don't get lost heaps of extension methods. ShouldBeNull(), ShouldBeTrue and ShouldBeFalse were all added after initial push back from me, I think justifying extensions needs to happen. Could you add example error messages for the open issues? (I am reopening the ones you think need further discussion)

What does `ShouldNotBeInAscendingOrder` do?

**Comment by ceregador** [comment]
_Example of an error message for ShouldBeInDescendingOrder():_
Expected collection to contain items in descending order, but found {1, 3, 5} where item at index 0 is in wrong order.

_Example of an error message for ShouldNotBeDescendingInOrder():_
Did not expect collection to contain items in descending order, but found {5, 3, 1}.

**Comment by JakeGinnivan** [comment]
When would you ever actually want `ShouldNotBeDescendingInOrder`?

Also, those exceptions are not shouldly exceptions. They don't take advantage of having the source available and don't match the format we have

**Comment by SurajGupta** [comment]
I think ShouldNotBeDescendingInOrder is a corner case, the first one is probably far more useful.  I didn't understand your point about not having the "source" available?

**Comment by JakeGinnivan** [comment]
I have updated the title. It would be good if you could have a good think about the error message @ceregador or @SurajGupta. We need a msg when the source is available and one which doesn't. Also, pull request? :)

**Comment by SimonCropp** [comment]
given https://github.com/shouldly/shouldly/pull/410 is merged i will close this
