### ISSUE TITLE
Initial line feed on exceptions

### ISSUE THREAD

**Issue by JakeGinnivan** [shouldly/shouldly#397]
I was having a read of http://www.daedtech.com/rethinking-assert-with-shouldly/

And it occurred to me that maybe we should put an initial line feed on shouldly exceptions so the `calculationResult` is on the second line under the exception type.

Thoughts?

**Comment by tdwright** [comment]
This would be my preference. I'm not usually interested in the fact that a `Shouldly.ShouldAssertException` (or whatever) has been thrown, but I'm super interested in knowing what value is wrong.

**Comment by dcgit** [comment]
Just to clarify, using the sample from the link, is the suggestion to have it display as:
```
Shouldly.ShouldAssertException:
calculationResult should be
  0d
but was
  20d
```

**Comment by JakeGinnivan** [comment]
Yeah exactly. At the moment the exception type and start of the message are in the same line.

Get Outlook for iOS<https://aka.ms/o0ukef>

________________________________

**Comment by KAW24** [comment]
I think #407 would be a better fix because it will also get rid of the full method name that is wrapped over 4 lines in the linked example.

**Comment by bdparrish** [comment]
Looking to tackle this and I see [DictionaryShouldContainKeyAndValueMessageGenerator.cs#L17](https://github.com/shouldly/shouldly/blob/cb58830180c1c3f87db9b0eb74ef9d7c446ec71e/src/Shouldly/MessageGenerators/DictionaryShouldContainKeyAndValueMessageGenerator.cs#L17).  Is this the correct format for these messages?  Some `MessageGenerators` have this format and some don't (i.e., [DynamicShouldMessageGenerator.cs#L30](https://github.com/shouldly/shouldly/blob/cda15112473b7df80baf0046541a2901095c2bf3/src/Shouldly/MessageGenerators/DynamicShouldMessageGenerator.cs#L30)).  Do these all need to be refactored to have a more generic refactor since all messages will have the same format?

**Comment by hemantkd** [comment]
Hi @JakeGinnivan,

I was wondering if I could contribute by fixing this issue but it seems like you're in the middle of upgrading the .NET version?
Is it best to wait until then it looks like the current build is failing?
I managed to for your repo in VS2017 and was able to build successfully but was not successful in running the unit tests. Is this a known issue?

Cheers

**Comment by cristianKumul** [comment]
Hello @JakeGinnivan , Is this issue still required? I can take a look at it

**Comment by JakeGinnivan** [comment]
Honestly I am not sure, it's been ages since I have contributed to shouldly and just don't have the context anymore. Sorry.

**Comment by SimonCropp** [comment]
given the timeline, and @JakeGinnivan last comment, i am closing this one for now.  happy to reopen if it still effects anyone
