### ISSUE TITLE
Drop support for .NET 3.5?

### ISSUE THREAD

**Issue by JosephWoodward** [shouldly/shouldly#442]
I've got a [pull request](https://github.com/shouldly/shouldly/pull/432) ready for migrating to the new MSBuild tooling and I'm thinking it's time we drop support for .NET 3.5. The reasons are:

- It'd be great to get Shouldly to a point where it's not only.NET Standard compliant but also people can contribute and build it locally from platforms other than Windows, this is a step in that direction.
- Supporting .NET 3.5 means adding a whole load of polyfills into the solution which complicates things
- Other assertion libraries such as FluentAssertions don't support 3.5 anymore
- Is anyone using 3.5 anymore?

I was thinking the next version would be a 3.0 release as a clean break from the 2x version, this would include a lot of the new pull requests including the [object graph comparison](https://github.com/shouldly/shouldly/pull/411) kindly done by @TaffarelJr that I know a lot of people are keen for Shouldly to have.

Thoughts anyone? cc @JakeGinnivan

**Comment by slang25** [comment]
@JosephWoodward you already know my view, but I'll say it here for the benefit of others.

I won't comment on who or how many people are using .NET 3.5, but I imagine there are some. Right now the AppVeyor build is happily outputting `net35`, `net40` & `net451` assemblies, and the polyfills are already in place.

When developing on a macOS, if the issue is that there is no support for `net35` cause there isn't a version of msbuild/xbuild + Mono that can produce the output, why not just conditionally disable those TFMs for that platform in the csproj. That way we still support net35, it's just that on macOS we find out on the pull request if it breaks that platform. This still moves in the direction of enabling developing on other platforms.

The current version of Mono only supports building net45 and up for the "Full Framework" (as I understand), so we are in the same situation with net40, we will need to either drop it, or accept it will only be built on the ci server.

Dropping 3.5 still leaves in most of the compiler constants, it goes from 9 down to 5.

The object graph comparison PR mentioned does not include anything that requires 3.5 polyfills, why not keep support, and drop it once it becomes an issue?

All that said, I am all for dropping .NET 3.5 cause like, it's really old!

**Comment by JosephWoodward** [comment]
I suppose the issue is how long do we keep supporting it for? We can keep adding conditionals around things and polluting the codebase to make it work but where do we draw the line and say it's had its time? Once it becomes an issue? If we keep adding conditionals around things then it's likely never going to be an issue and something we'll be dragging along with us for some time to come.

If we were to remove it it'd need to be a major version release, so do we hold off on 3 until we decide to remove it or keep it until we eventually release a 4?

![dunno](http://diabetesdad.org/files/2014/06/I-dunno.jpg)

**Comment by slang25** [comment]
Thoughts from @AnthonySteele

![image](https://user-images.githubusercontent.com/1341446/27854849-397bb1b2-6160-11e7-8f45-bc32422ec26b.png)

**Comment by slang25** [comment]
More comments via twitter:

![image](https://user-images.githubusercontent.com/1341446/27854898-69cece62-6160-11e7-8858-4916ce7867e9.png)
![image](https://user-images.githubusercontent.com/1341446/27854931-8282a1ae-6160-11e7-91ac-cdd3481c612a.png)
![image](https://user-images.githubusercontent.com/1341446/27854951-99d093de-6160-11e7-9623-57f74bb86cd2.png)

**Comment by JosephWoodward** [comment]
Shahid's point is very valid.

**Comment by slang25** [comment]
PR here to illustrate the benefit to the codebase in killing net35 #443

**Comment by JosephWoodward** [comment]
With the new .csproj format, keeping .NET 3.5 support complicates the toolchain a little more https://github.com/Microsoft/msbuild/issues/1333

**Comment by JosephWoodward** [comment]
.NET 3.5 support has been removed in the latest version [3.0 beta 1](https://www.nuget.org/packages/Shouldly/3.0.0-beta0001) which is now available on NuGet, though we'll continue to support 3.5 in older versions.

**Comment by jnm2** [comment]
Somewhat selfishly, since .NET 3.5 is still in use for some work projects that run under a larger third party platform, I'd like to add back in just a `net35` build beside our other builds. These days it's easy to build net35 cross-platform using `dotnet build` (well, [*now*](https://www.nuget.org/packages/jnm2.ReferenceAssemblies.net35/) it is). I'm familiar with doing this.

If you all don't mind putting up with a bit of `#if !NET35` here and there, it would be nice to consume things in our projects like the v4 nullable reference types annotations.

If you do mind, no worries, I get it. If you're targeting .NET 3.5, the day comes when there's a final version of every tool that you'll use from then on. That's to be expected.

**Comment by jnm2** [comment]
Oh, I should respond to this:

> ![](https://user-images.githubusercontent.com/1341446/27854951-99d093de-6160-11e7-9623-57f74bb86cd2.png)
>
> Shahid's point is a very good one.

.NET Framework 3.5 SP1 is very much in support by Microsoft as a Windows OS component and will be until 2029.
https://docs.microsoft.com/en-us/lifecycle/products/microsoft-net-framework
https://docs.microsoft.com/en-US/lifecycle/faq/dotnet-framework

To be clear, I don't think this means that therefore any .NET library should support .NET Framework 3.5. But it's a bit too strong to say that Microsoft doesn't even support it; Microsoft does.

**Comment by jnm2** [comment]
After trying this out, there were too many points against it for me. The main problem is that if you add a `net35` target to the package, `net461`+ projects begin preferring it over `netstandard2.0`, so at minimum we would probably be adding `;net461;net35`. Then that increases the test matrix complexity.

Another problem is that the combination of ReSharper + ReferenceAssemblyAnnotator + net35 results in a very poor experience in the Visual Studio code editor when the project selector is set to `(net35)`. ReSharper constantly cycles between thinking there are no reference assemblies and coloring all BCL types red, and rediscovering the reference assemblies and briefly being normal.

These, plus the 24 occurrences of `#if !NET35`, make me think that this is too much of a burden for this repo. A fork could publish a `Shouldly.Community.net35` (?) package to an internal feed or to nuget.org if it was worth it to someone.
