### ISSUE TITLE
ShouldBe() support for DateTime should include nullable DateTime

### ISSUE THREAD

**Issue by cottsak** [shouldly/shouldly#456]
`Convert.ToDateTime(tpInStore.Completed).ShouldBe(now, TimeSpan.FromSeconds(1));` kinda looks lame

**Comment by JosephWoodward** [comment]
Thanks for your post @cottsak, would you mind giving a clearer example explaining what you mean?

Is your `now` variable a nullable `DateTime`?, like below?

```csharp
DateTime dateTime = Convert.ToDateTime(DateTime.Now.ToString());
DateTime? nullableDateTime = DateTime.Now;
dateTime.ShouldBe(nullableDateTime, TimeSpan.FromSeconds(1));
```
Given your example, do you mean ShouldBe should accept a nullable datetime?

**Comment by jnm2** [comment]
In v4, we support assertions on nullable DateTime with tolerance parameters using the following syntax:

```cs
tpInStore.Completed.ShouldNotBeNull().ShouldBe(now, TimeSpan.FromSeconds(1));
```

I think the original request is asking for this shorthand syntax which would roll the not-null and tolerance checks into one:

```cs
tpInStore.Completed.ShouldBe(now, TimeSpan.FromSeconds(1));
```

We might be able to pull that off without adding any new overloads if we take `DateTime?` instead of `DateTime` as the extension method receiver parameter type, but I'm not convinced that the implicit null check is better than an explicit one.

Closing due to lack of response, but anyone can feel free to comment and we'll see and reopen to consider.
