### ISSUE TITLE
[string].ShouldStartWith ignores string length

### ISSUE THREAD

**Issue by minimaltesty** [shouldly/shouldly#483]
Shouldy V3.0.0
```
"﻿<?xml version="1.0" encoding="utf-16"?>".ShouldStartWith( "<?xml", Case.Insensitive );
```

This methods output is:
```Shouldly.ShouldAssertException : first
    should start with
"<?xml"
    but was
"﻿<?xml version="1.0" encoding="utf-16"?> ....
```

**Comment by JosephWoodward** [comment]
Thanks for reporting this, I'll take a look into it.

**Comment by grothar** [comment]
The string provided `"﻿<?xml version="1.0" encoding="utf-16"?>"` start with two Unicode Characters 'ZERO WIDTH NO-BREAK SPACE' (U+FEFF), which you can see if you do .ToCharArray().
I think the behavior of [string].ShouldStartWith is correct.

**Comment by andy-wojciechowski** [comment]
I agree with the comment above that the functionality of ShouldStartWith is correct. I got the string provided working however by using StringComparision.CurrentCultureIgnoreCase and StringComparision.CurrentCulture. InvariantCulture will not work since it's not available in .NET standard 1.3. Maybe this needs to be culture sensitive since unicode characters are involved? I was going to do some additional testing before creating a PR with this change.

**Comment by minimaltesty** [comment]
Thanks for your answer. You're completely correct. I did not see that difference. But when using

**Comment by grothar** [comment]
I just tried it with XUnit and it works the same as Shouldy.
Behind the hood ShouldStartWith with Case.Insensitive  uses StringComparison.OrdinalIgnoreCase which is the correct way to compare.

> An operation that uses ordinal sort rules performs a comparison based on the numeric value (Unicode code point) of each Char in the string. 

If you pass the same string comparison to XUnit it also fails.

```
// works
Assert.StartsWith("<?xml", "﻿<?xml version=\"1.0\" encoding=\"utf-16\"?>");
// fails
Assert.StartsWith("<?xml", "﻿<?xml version=\"1.0\" encoding=\"utf-16\"?>", StringComparison.OrdinalIgnoreCase);
```

**Comment by JosephWoodward** [comment]
Thanks a lot for the investigation on this @grothar, as a result I will close this issue.
