### ISSUE TITLE
Unable to open the project in VS2017.  Expected imports are missing.

### ISSUE THREAD

**Issue by xavierjohn** [shouldly/shouldly#491]
Opening the shoudly.sln in VS 2017 gives the following errors

shouldly\src\Shouldly\Shouldly.csproj : error  : Project file is incomplete. Expected imports are missing.

shouldly\src\Shouldly.Tests\Shouldly.Tests.csproj : error  : Project file is incomplete. Expected imports are missing.

shouldly\src\TestDiffTools\TestDiffTools.csproj : error  : Project file is incomplete. Expected imports are missing.

shouldly\src\DocumentationExamples\DocumentationExamples.csproj : error  : Project file is incomplete. Expected imports are missing.

Some of the properties associated with the solution could not be read.

**Comment by JosephWoodward** [comment]
Thanks for reporting this. What version of 2017 are you running out of interest? Is it clean version of the latest master branch?

**Comment by xavierjohn** [comment]
It is a clean version I cloned yesterday.

Microsoft Visual Studio Enterprise 2017 
Version 15.6.0
VisualStudio.15.Release/15.6.0+27428.1
Microsoft .NET Framework
Version 4.7.02556

**Comment by loneosama** [comment]
I am getting this error too. unfortunately I am having the feeling that after much trouble the final solution is to port the project from .net 4.5.2 to > .net standard 2.0 it is not compling for .net standard 2.0 and even 1.3. The problem is it is reading the configuration from project.json file. I think it has to be ported to csproj  before anything else

**Comment by JosephWoodward** [comment]
@loneosama Where are you seeing the project.json file?

**Comment by loneosama** [comment]
sorry the name is project.assets.json in Shouldly/obj folder. This is made after i build the project.

**Comment by JosephWoodward** [comment]
Oh okay, thanks

**Comment by loneosama** [comment]
@xavierjohn  aren't you still able to open it on visual studio 15.6 ?

**Comment by xavierjohn** [comment]
I get a different error in VS 2015.
Microsoft Visual Studio Enterprise 2015
Version 14.0.25431.01 Update 3
So I can't open in 2015 or 2017

shouldly\src\Shouldly\Shouldly.csproj : error  : The default XML namespace of the project must be the MSBuild XML namespace. If the project is authored in the MSBuild 2003 format, please add xmlns="http://schemas.microsoft.com/developer/msbuild/2003" to the <Project> element. If the project has been authored in the old 1.0 or 1.2 format, please convert it to MSBuild 2003 format.  C:\git\github\shouldly\src\Shouldly\Shouldly.csproj

**Comment by loneosama** [comment]
<Project xmlns="http://schemas.microsoft.com/developer/msbuild/2003" ToolsVersion="15.0">
add this to the project tag does this make it work?

**Comment by xavierjohn** [comment]
I ported Shouldly and its tests to VS 2017 and .netcore 2. There is one failing unit test. Hope it helps convert this project. https://github.com/xavierjohn/Shouldly

**Comment by loneosama** [comment]
@JosephWoodward  [](https://github.com/onovotny/MultiTargetTheWorld) i found this thing on the web and it is a really great way to ensure that our projects are run on all the frameworks not just the latest the pattern is really quite manageable. What you think should we port it to this format. We will basically make platform specific folders for the project and tests? @xavierjohn  if we were to port the project to 2.0 it would be a hassle to mantain it for 2.0 and .net framework seperately. Instead i think this way given by the author is a good one [](https://oren.codes/2017/01/04/multi-targeting-the-world-a-single-project-to-rule-them-all/)

**Comment by xavierjohn** [comment]
A better way is to target netstandard2.0 so that it works for .net and .netcore. I have updated the code.

**Comment by loneosama** [comment]
a read a blog and it said that netstandard2.0 is fully implemented by .net core so a project targeting .net standard 2.0 does not need to target dotnet core. But a problem come with the .net framework as there are still some compatibility issues with .net standard and the full dotnet frameworks <= 4.6.1 so it is better to target net 46 and net 45 separately and target netstandard2.0 only instead of netstandard2.0 and netcoreapp2.0. i researched a lot today, i think the current project can be fixed because there is only a little conflicting code that has to be dealt with, but i am still unable to figure out what the Documentation Examples Project does. If i had some insight on that i would be able to tell you with more assurity . but yeah we can port it if we want to and it would clean the project from many legacy things and clean up csproj file a bit. so yeah i would also like to hear @JosephWoodward opnion about it because i am new to open source so dont know what should we do in these sort of things

**Comment by hemantkd** [comment]
Hi @JosephWoodward,

I'm using VS 2017 version 15.6.4
I'm running the latest copy of your master which I had forked here: https://github.com/hemantkd/shouldly

Everything builds fine.
But, I am getting 6 warnings and one of them is the following:
4>Z:\XXX\repos\Shouldly\src\Shouldly.Tests\Shouldly.Tests.csproj : warning NU1701: Package 'TestStack.ConventionTests 3.0.1' was restored using '.NETFramework,Version=v4.6.1' instead of the project target framework '.NETCoreApp,Version=v2.0'. This package may not be fully compatible with your project.

And, I'm getting 50+ tests failing. Are they all supposed to pass?
Thanks for your help in advance.


[If this is not the thread to discuss this, I can create a new one.]

**Comment by loneosama** [comment]
open a new one because i am trying to fix this issue apprantely the issue is that StackFrame class is returning null on the method GetFileName in DocumentExampleWriter.cs

**Comment by loneosama** [comment]
I have created  a pull request and now all the tests pass except few approval tests for that just run the command given in the exception for it to pass @hemantkd  @xavierjohn

**Comment by JosephWoodward** [comment]
This should now be fixed, please let me know if it's still an issue.
