### ISSUE TITLE
Target .NET Standard 2.0

### ISSUE THREAD

**Issue by eloekset** [shouldly/shouldly#517]
According to this Twitter thread, the documentation isn't updated, but all libraries should target netstandard2.0 in addition to lower standards (if supported) to minimize dependency hell for users of the library: https://twitter.com/davidfowl/status/1025434242832945154

Shouldly.csproj already has netstandard2.0 in targetframeworks, but the latest released NuGet package doesn't have that option:
![image](https://user-images.githubusercontent.com/791721/43825595-75e4b372-9af5-11e8-9515-826a82d8bd48.png)

Maybe release a 3.1.0 or 3.0.1 to support that target?

**Comment by StefanKoenen** [comment]
@JosephWoodward Is there any update on this, because I want to contribute :)

Another question related to this, I tried to update myself, but it looks like these lines of code are disabling the target framework dropdown in project properties.
`    <TargetFrameworks>netstandard2.0</TargetFrameworks>
<TargetFrameworks Condition=" '$(OS)' != 'Windows_NT' ">netstandard2.0</TargetFrameworks>`

Do you know what the issue is?

**Comment by JosephWoodward** [comment]
@StefanKoenen Which project are you seeing that in?

There are these lines:

```xml
<TargetFrameworks>net451;net40;netstandard1.3;netstandard2.0</TargetFrameworks>
<TargetFrameworks Condition=" '$(OS)' != 'Windows_NT' ">netstandard1.3;netstandard2.0</TargetFrameworks>
```

Which enable anyone not on Windows (such as myself) to successfully build Shouldly.

Is this what you're referring to?

**Comment by JosephWoodward** [comment]
A little late, but been super busy lately but I've pushed the .NET Standard 2.0 support changes as part of [Shouldly 3.0.1 which can be downloaded here](https://www.nuget.org/packages/Shouldly/3.0.1).

**Comment by StefanKoenen** [comment]
@JosephWoodward 
I just did a clean checkout to answer your question. (I think in my post I already updated the lines)
1. With the two lines enabled in the .csproj file
![image](https://user-images.githubusercontent.com/1442819/45845281-06c7d800-bd25-11e8-887f-0456d02350f0.png)
2. With the lines disabled... not sure if the dropdown is correct
![image](https://user-images.githubusercontent.com/1442819/45845327-1d6e2f00-bd25-11e8-8596-7d31b9c134c4.png)

**Comment by StefanKoenen** [comment]
> A little late, but been super busy lately but I've pushed the .NET Standard 2.0 support changes as part of [Shouldly 3.0.1 which can be downloaded here](https://www.nuget.org/packages/Shouldly/3.0.1).

The link isn't working ;)

**Comment by JosephWoodward** [comment]
@StefanKoenen Hmmm, I'd be inclined to say that's a bug in Visual Studio. It seems like it's valid for msbuild as it builds it depending on the platform you're on, but clearly the tooling in Visual Studio can't deal with it.

The issue is if you remove the line with the condition on it then I can't build it on the mac without having to specify the target framework, so it might just be worth commenting out that bottom line in the mean time?

**Comment by StefanKoenen** [comment]
@JosephWoodward 
I think I agree with you about the VS bug, I will do that for now. Thanks for your time!
