### ISSUE TITLE
Getting started

### ISSUE THREAD

**Issue by snehansh** [shouldly/shouldly#525]
I am new here. I fork and clone repo and using the link: https://shouldly.readthedocs.io/en/latest/contributing.html tried to generate the build. I get several warnings like:

`C:\Repos\shouldly\docs\assertions\shouldBe.rst:8: WARNING: Include file 'C:\\Repos\\shouldly\\src\\DocumentationExamples\\CodeExamples\\ShouldBeExamples\\Objects.codeSample.approved.txt' not found or reading it failed`

Upon running the tests from VS 2017 project 'Shouldly.Tests' all the tests under 'Documentation Examples' failed. 

I do not know if I need to fix these before beginning to work in the Shouldly project. Please guide me on how to get started and contribute. Thanks.

**Comment by loneosama** [comment]
the thing is that the pull request #503 solves the problem adding a line to the csproj file of documentation examples and then all the documentation examples work. There are many pull requests that are in the pipeline that will solve most of the problems that are there. I pushed some pull requests if you fork my latest pull request your problem should be solved.

**Comment by loneosama** [comment]
@snehansh  the thing is that if you want to learn this project and how to contribute to it. this will take some time because the documention on getting started for developers is a bit lacking. I would suggest first try to play around with the project and make sure everything is working before moving on to solve issues. If you need personal help contact me on my email osama.arif@khi.iba.edu.pk i ll be happy to help as much as i can.

**Comment by JosephWoodward** [comment]
@snehansh @loneosama is right, there may be some of it that's out of date, and there's a couple of pull requests in the pipeline that should fix some of this stuff. Unfortunately I've been really busy recently so still catching up.

**Comment by snehansh** [comment]
thanks. i will close this issue, since i got a lot of information to start.
