### ISSUE TITLE
too many extensions on basic type,i prefer obj.Should().notnull();

### ISSUE THREAD

**Issue by hiwjcn** [shouldly/shouldly#594]
when we type via vs,too many suggestion appear at once.
can we make api look like this:
```
obj.Should().notnull();
```
in this way,only one extension method be suggested.

**Comment by JosephWoodward** [comment]
I think you're looking for [the community over at FluentAssertions](https://github.com/fluentassertions/fluentassertions).

We have `obj.ShouldNotBeNull()`.

**Comment by JosephWoodward** [comment]
Closing the issue as I believe you're posting in the wrong place, if I'm mistake then we could discuss further, but we'd rather not break the `ShouldBeX` convention that exists. One of the reason people prefer Shouldly over FluentAssertions is because the decision not go have long method chains.

**Comment by jnm2** [comment]
Shouldly's decision to have a single method call, `ShouldNotBeNull()`, turned out to be incredibly lucky when C# 8 came out with the Nullable Reference Types feature. It's possible to annotate `expr.ShouldNotBeNull()` so that the compiler knows that `expr` is not null after that statement (and we did this in v4). It's not possible to do the same thing with `expr.Should().NotBeNull()` with the annotations that the C# compiler recognizes.
