### ISSUE TITLE
ShouldBe() on two simple objects failing

### ISSUE THREAD

**Issue by rubans** [shouldly/shouldly#616]
I have the following code :
`
var expect = new Dummy()
{
    Prop = 1,
};
var actual = new Dummy()
{
    Prop = 1
};
actual.ShouldBeSameAs(expect);
`
I have similar example elsewhere of this working so I would assume this should be working but I get an exception:
Shouldly.ShouldAssertException : actual
        should be same as
    UnitTests.Dummy (56005557)
        but was
    UnitTests.Dummy (16433012)
Let me know if further information is required?

**Comment by JosephWoodward** [comment]
Thanks for reporting this. The `ShouldBeSameAs` feature is still in its infancy so reports like this are really valuable.

**Comment by amandal1810** [comment]
@rubans  as far as i can see from the code and unit test cases, the `ShouldBeSameAs` feature is supposed to compare the object references and not the properties of the objects. 

@JosephWoodward and owners of this project: what should be the intended expectation from the `ShouldBeSameAs` feature? Should it look at the object properties?

**Comment by meJevin** [comment]
@JosephWoodward I have the same question as @amandal1810. What does that feature do?

**Comment by JosephWoodward** [comment]
@meJevin @rubans Hi, sorry for the delay. I was getting my methods mixed up, `ShouldBeSameAs` does a referencial check on the types so that test is expected to fail. If you're looking to compare if the two objects are equivalent then you can use the `ShouldBeEquivalentTo` assertion in the latest preview. It's this extension which is a new feature that I refer to in my first comment.

**Comment by JosephWoodward** [comment]
I'm going to close off this issue but please feel free to response with any further questions.
