### ISSUE TITLE
Drop support for netstandard1.3 and net451

### ISSUE THREAD

**Issue by SimonCropp** [shouldly/shouldly#638]
and only support netstandard2.0 and up. still gives pretty good coverage https://docs.microsoft.com/en-us/dotnet/standard/net-standard

@JosephWoodward thoughts?

**Comment by SimonCropp** [comment]
@JakeGinnivan @jnm2 slang25 thoughts?

**Comment by jnm2** [comment]
The net difference when removing netstandard1.3 is dropping support for .NET Core 1.0 (Microsoft no longer supports it), certain versions of Xamarin, and UWP 10.0. IIRC there is no reason not to move to the version of UWP that supports netstandard2.0 since it runs on all versions of Windows that Microsoft currently supports.

The net difference when removing net451 is that people who target net451-net46 will have to move. I think net452 is still supported by Microsoft ([doc](https://docs.microsoft.com/en-us/lifecycle/faq/dotnet-framework#what-is-the-lifecycle-policy-for-different-versions-of-the-net-framework)), but another thing to consider is that all versions of Windows 10 supported by Microsoft have net472 installed through Windows Update and soon that will be net48. (Based on the rule that you're explicitly out of support if you're more than a year behind the biannual updates. This doesn't cover Windows Server.)

(I'm saying "Microsoft supports" a lot for information. That doesn't dictate Shouldly's options in either direction. xUnit 3.0.0's only .NET Framework build will be net472 because that's its thing, and NUnit still supports net35 because that's its thing.)

**Comment by SimonCropp** [comment]
also we are in a test context here. if people are in a pinch, they can still target net451-net46 in prod, but test against 461. i suspect most OSS projects dont test against all their supported runtimes anyway

**Comment by SimonCropp** [comment]
>  NUnit still supports net35 because that's its thing.

as an aside i wish it didnt. i extend nunit in a couple of projects. and people expect those projects to support net35 simply because nunit does

**Comment by slang25** [comment]
I agree with what's been said here. A year ago I might have had a different answer, but today everything below TFMs supporting netstandard2.0 are in maintenance mode, and I can't see there being a good reason to not update test projects to a more supported framework runtime where necessary.

**Comment by jnm2** [comment]
One reason could be that the framework behaves differently due to behavior quirking. Here is a list of what changes: https://docs.microsoft.com/en-us/dotnet/framework/migration-guide/retargeting/4.5.1-4.6.1

**Comment by SimonCropp** [comment]
well i guess we can target 472 or target lower and issue the same warning

**Comment by SimonCropp** [comment]
how about this

 * release a beta with only netstandard2. publicise the fact that this is coming. see if anyone has legit objections, if the do we can re add some lower runtimes
 * if there are no objections, release a stable. then again, if there are legit objections we can re-add some lower runtimes

**Comment by SimonCropp** [comment]
@JosephWoodward r u ok with the above plan?

**Comment by JosephWoodward** [comment]
@SimonCropp Yeah, sounds like.a good idea. Perhaps we keep this issue open for people to raise objections along the way?

**Comment by jnm2** [comment]
Should this issue be closed now that #643 is merged?

I'd love to have a beta to play around with btw, whenever the breaking changes have mostly settled.

**Comment by SimonCropp** [comment]
@jnm2 it is open since @JosephWoodward requested it to remain open. I am happy to close

and i wanted to get this resolved before doing a beta https://github.com/shouldly/shouldly/pull/644

**Comment by jnm2** [comment]
Oh, ignore me. I remember reading that but I missed it this time through.

**Comment by SimonCropp** [comment]
ok i am going to close this. it is in the 4 milestone so people can see it as part of the change list
