### ISSUE TITLE
Error: "Shouldly uses your source code to generate its great error messages"

### ISSUE THREAD

**Issue by patriksvensson** [shouldly/shouldly#657]
Started seeing errors in my builds on Windows (Linux and MacOS seems to be fine) when running my tests in Release mode, and not for every test, just a couple of them. I can't reproduce this locally, only in GitHub Actions.

```
  X Spectre.Cli.Tests.CommandAppTests.Should_Throw_If_Alias_Conflicts_With_Another_Command [221ms]
  Error Message:
   Shouldly.ShouldAssertException : Shouldly uses your source code to generate its great error messages, 
   build your test project with full debug information to get better error messages
```

Link to build here for more context: https://github.com/spectresystems/spectre.cli/runs/1045311427?check_suite_focus=true

Haven't seen this before, is it some kind of regression in Shouldy?

**Comment by slang25** [comment]
I'll take a quick look and see if I can replicate. There are a few factors that can produce that message, and the message itself isn't quite accurate.

Shouldy walks the stack to try to find your method, and the place where the assertion was specified. This relies on debug builds (to prevent inlining etc...) and debug symbols being loaded (not "Full" as specified in the message).

There have been changes to this since 3.0.2, so it could be worth trying a beta and seeing if that fixes it.

**Comment by patriksvensson** [comment]
@slang25 I understand. And after digging into the code a bit I realize this is my own mistake. Closing the issue.

**Comment by slang25** [comment]
I'm really curious about the ci issue though, it happens every time in CI, but I can't replicate it locally (same SDK version, same commands and everything!), and it should be able to use debug symbols here, I don't get what is going on.

**Comment by patriksvensson** [comment]
@slang25 It's an exception in another assembly that tries to get `System.Console.BufferWidth`. NCrunch and `dotnet test` returns an actual ConsoleHandle, while GitHub Actions on Windows does not, so it throws. Looks like I haven't built the other assembly (Spectre.Console) with all debug symbols.

**Comment by patriksvensson** [comment]
Working on a fix for this now. But as a side note, I noticed that there is a `ShouldlyConfiguration.DisableSourceInErrors` that disables this via the current call context. Would be awesome if there was a way of disabling this for a whole assembly somehow.

**Comment by deanis74** [comment]
I'm curious about this error as well. Like so many others out there, my testers receive this message but I never do - "cannot reproduce". This has nothing to do with whether they have the pdb files. I don't receive this message because I have the full source file.

The message is generated in [SourceCodeTextGetter.cs](https://github.com/shouldly/shouldly/blob/master/src/Shouldly/Internals/SourceCodeTextGetter.cs#L58). And when the code runs on my dev box, `_determinedOriginatingFrame` will be `true`, because ` _determinedOriginatingFrame = fileName != null && File.Exists(fileName)`. So basically it's `true` because the source file exists on my local dev box and `false` on my testers' test boxes because they don't have the source files. And because it's false the stack is never walked and `codePart` is never changed from the default message about needing to be built with debug information.

So tell me I'm wrong, but this less to do with being built with debug information and more to do with being shipped with the original source files in the exact same directory structure as on the dev / build box. Which is very likely impossible.

**Comment by slang25** [comment]
@deanis74 you might have a scenario where you build and move your tests somewhere, then run them on a different machine, but generally this isn't how tests are usually ran. This is an implicit assumption I've been making, but I think it's good to call it out.

In the cases that have been reported so far, I am under the understanding that some variant of `dotnet test` is ran, and the at runtime there isn't sufficient metadata (i.e. loaded symbols) to determine where the source lives. So in this scenario the assemblies are built from the source implicitly before being run.

Another thing that you've got me thinking about is `ContinuousIntegrationBuild`, which when enabled in a project file will sanitise the source file paths to not point to a full path on the machine it was built on (to enable reproducible builds). In this case the `File.Exists(fileName)` call you refer to would fail, we might need to make this clear in the docs.

**Comment by deanis74** [comment]
@slang25 that's the exact situation I have. And I've been trying to chase down why my testers were encountering that error even though my step definitions project was built with full debug info. I don't think that's an entirely unusual situation to encounter, so at the very least the message of does not match the requirements of needing the original source file in its original location.

**Comment by slang25** [comment]
I think the message is the biggest problem with this feature, it is supposed to be a light-up feature, i.e. if we can display the expression being asserted on, great! let's show it! If not, no big deal. If the intended usage is to use Shouldly and build an assembly on one machine, and then run it on another, this functionality should not be expected to work, and Shouldly shouldn't make a fuss about it.

Something that completely solves this complexity is using the C# 10 feature [CallerArgumentExpression](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/proposals/csharp-10.0/caller-argument-expression). This would solve it for your use case too, and would be completely trivial at runtime as it's all handled at compilation.

Unfortunately it would only work with users running the .NET 6 SDK and up, we would leave this existing implementation as a fallback for those on a lower version. Another unfortunate thing is that because Shouldly doesn't have a single entrypoint (like FluentAssertions) then we'd have to change *all* of the extension methods. I think it's worth looking at though.
