### ISSUE TITLE
Rename ShouldBeTypeOf 

### ISSUE THREAD

**Issue by JakeGinnivan** [shouldly/shouldly#98]
So far the options are:
- ShouldBeInstanceOf<T>()
- ShouldBeType<T>()
- ShouldBeOfType<T>()
- ShouldBe<T>
- ShouldBeA<T>

I am leaning towards ShouldBeInstanceOf as that is the same as most assertion frameworks

**Comment by cottsak** [comment]
Ugh!

I'm so disappointed on how this turned out.

1. Is there any concrete evidence that we needed a "specific type" method when the "type and all derived" would do?
2. `.ShouldBeA()` reads so much better than `.ShouldBeOfType<T>()` or `.ShouldBeAssignableTo<T>()`
3. Normally I would side with "convention == usability" however adopting the "OfType" and "AssignableTo" nomenclature because it's what the 100-year-old reflection namespaces (and other test frameworks!?) used is so archaic. I mean, I accept that #namingishard and all, but that's what this discussion was for and you all came so close to throwing those old, and cognitively expensive terms out.
4. Shouldly `.ShouldHaveAPointOfDifference()` and this change is burning that IMO.

:sob:
